'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3620
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by wsdl, Version=2.0.50727.3038.
'

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038"), _
 System.Diagnostics.DebuggerStepThroughAttribute(), _
 System.ComponentModel.DesignerCategoryAttribute("code"), _
 System.Web.Services.WebServiceBindingAttribute(Name:="Service1Soap", [Namespace]:="http://tempuri.org/")> _
Partial Public Class AdminProxyService
    Inherits System.Web.Services.Protocols.SoapHttpClientProtocol

    Private HelloWorldOperationCompleted As System.Threading.SendOrPostCallback

    Private CheckUserPendingBeneficiariesOperationCompleted As System.Threading.SendOrPostCallback

    Private CancelUserBeneficiariesOperationCompleted As System.Threading.SendOrPostCallback

    Private PendUserBeneficiariesOperationCompleted As System.Threading.SendOrPostCallback

    '''<remarks/>
    Public Sub New()

        MyBase.New()

        Me.Url = Convert.ToString(System.Configuration.ConfigurationSettings.AppSettings("Admin_WS_Path")).Trim()

    End Sub

    '''<remarks/>
    Public Event HelloWorldCompleted As HelloWorldCompletedEventHandler

    '''<remarks/>
    Public Event CheckUserPendingBeneficiariesCompleted As CheckUserPendingBeneficiariesCompletedEventHandler

    '''<remarks/>
    Public Event CancelUserBeneficiariesCompleted As CancelUserBeneficiariesCompletedEventHandler

    '''<remarks/>
    Public Event PendUserBeneficiariesCompleted As PendUserBeneficiariesCompletedEventHandler

    '''<remarks/>
    <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)> _
    Public Function HelloWorld() As String
        Dim results() As Object = Me.Invoke("HelloWorld", New Object(-1) {})
        Return CType(results(0), String)
    End Function

    '''<remarks/>
    Public Function BeginHelloWorld(ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        Return Me.BeginInvoke("HelloWorld", New Object(-1) {}, callback, asyncState)
    End Function

    '''<remarks/>
    Public Function EndHelloWorld(ByVal asyncResult As System.IAsyncResult) As String
        Dim results() As Object = Me.EndInvoke(asyncResult)
        Return CType(results(0), String)
    End Function

    '''<remarks/>
    Public Overloads Sub HelloWorldAsync()
        Me.HelloWorldAsync(Nothing)
    End Sub

    '''<remarks/>
    Public Overloads Sub HelloWorldAsync(ByVal userState As Object)
        If (Me.HelloWorldOperationCompleted Is Nothing) Then
            Me.HelloWorldOperationCompleted = AddressOf Me.OnHelloWorldOperationCompleted
        End If
        Me.InvokeAsync("HelloWorld", New Object(-1) {}, Me.HelloWorldOperationCompleted, userState)
    End Sub

    Private Sub OnHelloWorldOperationCompleted(ByVal arg As Object)
        If (Not (Me.HelloWorldCompletedEvent) Is Nothing) Then
            Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg, System.Web.Services.Protocols.InvokeCompletedEventArgs)
            RaiseEvent HelloWorldCompleted(Me, New HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
        End If
    End Sub

    '''<remarks/>
    <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CheckUserPendingBeneficiaries", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)> _
    Public Function CheckUserPendingBeneficiaries(ByVal inparameter As String) As String
        Dim results() As Object = Me.Invoke("CheckUserPendingBeneficiaries", New Object() {inparameter})
        Return CType(results(0), String)
    End Function

    '''<remarks/>
    Public Function BeginCheckUserPendingBeneficiaries(ByVal inparameter As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        Return Me.BeginInvoke("CheckUserPendingBeneficiaries", New Object() {inparameter}, callback, asyncState)
    End Function

    '''<remarks/>
    Public Function EndCheckUserPendingBeneficiaries(ByVal asyncResult As System.IAsyncResult) As String
        Dim results() As Object = Me.EndInvoke(asyncResult)
        Return CType(results(0), String)
    End Function

    '''<remarks/>
    Public Overloads Sub CheckUserPendingBeneficiariesAsync(ByVal inparameter As String)
        Me.CheckUserPendingBeneficiariesAsync(inparameter, Nothing)
    End Sub

    '''<remarks/>
    Public Overloads Sub CheckUserPendingBeneficiariesAsync(ByVal inparameter As String, ByVal userState As Object)
        If (Me.CheckUserPendingBeneficiariesOperationCompleted Is Nothing) Then
            Me.CheckUserPendingBeneficiariesOperationCompleted = AddressOf Me.OnCheckUserPendingBeneficiariesOperationCompleted
        End If
        Me.InvokeAsync("CheckUserPendingBeneficiaries", New Object() {inparameter}, Me.CheckUserPendingBeneficiariesOperationCompleted, userState)
    End Sub

    Private Sub OnCheckUserPendingBeneficiariesOperationCompleted(ByVal arg As Object)
        If (Not (Me.CheckUserPendingBeneficiariesCompletedEvent) Is Nothing) Then
            Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg, System.Web.Services.Protocols.InvokeCompletedEventArgs)
            RaiseEvent CheckUserPendingBeneficiariesCompleted(Me, New CheckUserPendingBeneficiariesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
        End If
    End Sub

    '''<remarks/>
    <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CancelUserBeneficiaries", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)> _
    Public Function CancelUserBeneficiaries(ByVal inparameter As String) As String
        Dim results() As Object = Me.Invoke("CancelUserBeneficiaries", New Object() {inparameter})
        Return CType(results(0), String)
    End Function

    '''<remarks/>
    Public Function BeginCancelUserBeneficiaries(ByVal inparameter As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        Return Me.BeginInvoke("CancelUserBeneficiaries", New Object() {inparameter}, callback, asyncState)
    End Function

    '''<remarks/>
    Public Function EndCancelUserBeneficiaries(ByVal asyncResult As System.IAsyncResult) As String
        Dim results() As Object = Me.EndInvoke(asyncResult)
        Return CType(results(0), String)
    End Function

    '''<remarks/>
    Public Overloads Sub CancelUserBeneficiariesAsync(ByVal inparameter As String)
        Me.CancelUserBeneficiariesAsync(inparameter, Nothing)
    End Sub

    '''<remarks/>
    Public Overloads Sub CancelUserBeneficiariesAsync(ByVal inparameter As String, ByVal userState As Object)
        If (Me.CancelUserBeneficiariesOperationCompleted Is Nothing) Then
            Me.CancelUserBeneficiariesOperationCompleted = AddressOf Me.OnCancelUserBeneficiariesOperationCompleted
        End If
        Me.InvokeAsync("CancelUserBeneficiaries", New Object() {inparameter}, Me.CancelUserBeneficiariesOperationCompleted, userState)
    End Sub

    Private Sub OnCancelUserBeneficiariesOperationCompleted(ByVal arg As Object)
        If (Not (Me.CancelUserBeneficiariesCompletedEvent) Is Nothing) Then
            Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg, System.Web.Services.Protocols.InvokeCompletedEventArgs)
            RaiseEvent CancelUserBeneficiariesCompleted(Me, New CancelUserBeneficiariesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
        End If
    End Sub

    '''<remarks/>
    <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PendUserBeneficiaries", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)> _
    Public Function PendUserBeneficiaries(ByVal inparameter As String) As String
        Dim results() As Object = Me.Invoke("PendUserBeneficiaries", New Object() {inparameter})
        Return CType(results(0), String)
    End Function

    '''<remarks/>
    Public Function BeginPendUserBeneficiaries(ByVal inparameter As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        Return Me.BeginInvoke("PendUserBeneficiaries", New Object() {inparameter}, callback, asyncState)
    End Function

    '''<remarks/>
    Public Function EndPendUserBeneficiaries(ByVal asyncResult As System.IAsyncResult) As String
        Dim results() As Object = Me.EndInvoke(asyncResult)
        Return CType(results(0), String)
    End Function

    '''<remarks/>
    Public Overloads Sub PendUserBeneficiariesAsync(ByVal inparameter As String)
        Me.PendUserBeneficiariesAsync(inparameter, Nothing)
    End Sub

    '''<remarks/>
    Public Overloads Sub PendUserBeneficiariesAsync(ByVal inparameter As String, ByVal userState As Object)
        If (Me.PendUserBeneficiariesOperationCompleted Is Nothing) Then
            Me.PendUserBeneficiariesOperationCompleted = AddressOf Me.OnPendUserBeneficiariesOperationCompleted
        End If
        Me.InvokeAsync("PendUserBeneficiaries", New Object() {inparameter}, Me.PendUserBeneficiariesOperationCompleted, userState)
    End Sub

    Private Sub OnPendUserBeneficiariesOperationCompleted(ByVal arg As Object)
        If (Not (Me.PendUserBeneficiariesCompletedEvent) Is Nothing) Then
            Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg, System.Web.Services.Protocols.InvokeCompletedEventArgs)
            RaiseEvent PendUserBeneficiariesCompleted(Me, New PendUserBeneficiariesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
        End If
    End Sub

    '''<remarks/>
    Public Shadows Sub CancelAsync(ByVal userState As Object)
        MyBase.CancelAsync(userState)
    End Sub
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")>  _
Public Delegate Sub HelloWorldCompletedEventHandler(ByVal sender As Object, ByVal e As HelloWorldCompletedEventArgs)

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038"),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code")>  _
Partial Public Class HelloWorldCompletedEventArgs
    Inherits System.ComponentModel.AsyncCompletedEventArgs
    
    Private results() As Object
    
    Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
        MyBase.New(exception, cancelled, userState)
        Me.results = results
    End Sub
    
    '''<remarks/>
    Public ReadOnly Property Result() As String
        Get
            Me.RaiseExceptionIfNecessary
            Return CType(Me.results(0),String)
        End Get
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")>  _
Public Delegate Sub CheckUserPendingBeneficiariesCompletedEventHandler(ByVal sender As Object, ByVal e As CheckUserPendingBeneficiariesCompletedEventArgs)

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038"),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code")>  _
Partial Public Class CheckUserPendingBeneficiariesCompletedEventArgs
    Inherits System.ComponentModel.AsyncCompletedEventArgs
    
    Private results() As Object
    
    Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
        MyBase.New(exception, cancelled, userState)
        Me.results = results
    End Sub
    
    '''<remarks/>
    Public ReadOnly Property Result() As String
        Get
            Me.RaiseExceptionIfNecessary
            Return CType(Me.results(0),String)
        End Get
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")>  _
Public Delegate Sub CancelUserBeneficiariesCompletedEventHandler(ByVal sender As Object, ByVal e As CancelUserBeneficiariesCompletedEventArgs)

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038"),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code")>  _
Partial Public Class CancelUserBeneficiariesCompletedEventArgs
    Inherits System.ComponentModel.AsyncCompletedEventArgs
    
    Private results() As Object
    
    Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
        MyBase.New(exception, cancelled, userState)
        Me.results = results
    End Sub
    
    '''<remarks/>
    Public ReadOnly Property Result() As String
        Get
            Me.RaiseExceptionIfNecessary
            Return CType(Me.results(0),String)
        End Get
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")>  _
Public Delegate Sub PendUserBeneficiariesCompletedEventHandler(ByVal sender As Object, ByVal e As PendUserBeneficiariesCompletedEventArgs)

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038"),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code")>  _
Partial Public Class PendUserBeneficiariesCompletedEventArgs
    Inherits System.ComponentModel.AsyncCompletedEventArgs
    
    Private results() As Object
    
    Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
        MyBase.New(exception, cancelled, userState)
        Me.results = results
    End Sub
    
    '''<remarks/>
    Public ReadOnly Property Result() As String
        Get
            Me.RaiseExceptionIfNecessary
            Return CType(Me.results(0),String)
        End Get
    End Property
End Class
