'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option or rebuild the Visual Studio project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class AddAdditionalAccounts
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Resources.AddAdditionalAccounts", Global.System.Reflection.[Assembly].Load("App_GlobalResources"))
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The new record you are trying to add is overlapping with an existing elective..
        '''</summary>
        Friend Shared ReadOnly Property MESSAGE_ACTIVE_RECORD_EXIST() As String
            Get
                Return ResourceManager.GetString("MESSAGE_ACTIVE_RECORD_EXIST", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Since the next elective record is in continuation with this one, its effective date will be changed 
        '''from {0} to {1}. Do you wish to continue?.
        '''</summary>
        Friend Shared ReadOnly Property MESSAGE_DO_YOU_WISH_TO_CHANGE_EFFECTIVE_DATE_OF_ACTIVE_RECORD() As String
            Get
                Return ResourceManager.GetString("MESSAGE_DO_YOU_WISH_TO_CHANGE_EFFECTIVE_DATE_OF_ACTIVE_RECORD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please enter date less than {0}  {1} from today.
        '''</summary>
        Friend Shared ReadOnly Property MESSAGE_ENTER_DATE_LESS_THAN_DAYSMONTHS_FROM_TODAY() As String
            Get
                Return ResourceManager.GetString("MESSAGE_ENTER_DATE_LESS_THAN_DAYSMONTHS_FROM_TODAY", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please enter date less than .
        '''</summary>
        Friend Shared ReadOnly Property MESSAGE_ENTER_DATE_LESS_THAN_EFFECTIVE_DATE_OF_ACTIVE_RECORD() As String
            Get
                Return ResourceManager.GetString("MESSAGE_ENTER_DATE_LESS_THAN_EFFECTIVE_DATE_OF_ACTIVE_RECORD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please enter date less than or equal to employee termination  date.
        '''</summary>
        Friend Shared ReadOnly Property MESSAGE_ENTER_DATE_LESS_THAN_EMPLOYMENT_TERMINATION_DATE() As String
            Get
                Return ResourceManager.GetString("MESSAGE_ENTER_DATE_LESS_THAN_EMPLOYMENT_TERMINATION_DATE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Non active participant can not keep termination date blank.
        '''</summary>
        Friend Shared ReadOnly Property MESSAGE_NON_ACTIVE_PARTICIPANT_CANNOT_KEEP_TERMINATION_DATE_BLANK() As String
            Get
                Return ResourceManager.GetString("MESSAGE_NON_ACTIVE_PARTICIPANT_CANNOT_KEEP_TERMINATION_DATE_BLANK", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
