'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34209
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option or rebuild the Visual Studio project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class NonRetiredQDRO
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Resources.NonRetiredQDRO", Global.System.Reflection.[Assembly].Load("App_GlobalResources"))
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Participant account is locked. Please refer to Customer Service Supervisor. .
        '''</summary>
        Friend Shared ReadOnly Property MESSAGE_ACCOUNT_IS_LOCKED() As String
            Get
                Return ResourceManager.GetString("MESSAGE_ACCOUNT_IS_LOCKED", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The requested split will result in a negative balance in one or more of the participant&apos;s accounts. Modify the split and try again..
        '''</summary>
        Friend Shared ReadOnly Property MESSAGE_CURRENTBALVALIDATION() As String
            Get
                Return ResourceManager.GetString("MESSAGE_CURRENTBALVALIDATION", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;br/&gt; Unable to create benificiary refund request, please create it manually. .
        '''</summary>
        Friend Shared ReadOnly Property MESSAGE_QDRO() As String
            Get
                Return ResourceManager.GetString("MESSAGE_QDRO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Participant account is locked due to {0}. Please refer to Customer Service Supervisor. .
        '''</summary>
        Friend Shared ReadOnly Property MESSAGE_QDRO_ACCOUNT_LOCKED_WITH_REASON() As String
            Get
                Return ResourceManager.GetString("MESSAGE_QDRO_ACCOUNT_LOCKED_WITH_REASON", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please select the Account(s) to Split .
        '''</summary>
        Friend Shared ReadOnly Property MESSAGE_QDRO_ACCOUNT_SPLIT() As String
            Get
                Return ResourceManager.GetString("MESSAGE_QDRO_ACCOUNT_SPLIT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Do you want to add another Recipient? .
        '''</summary>
        Friend Shared ReadOnly Property MESSAGE_QDRO_ADD_ANOTHER_BENEFICIARY() As String
            Get
                Return ResourceManager.GetString("MESSAGE_QDRO_ADD_ANOTHER_BENEFICIARY", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please add Recipient. .
        '''</summary>
        Friend Shared ReadOnly Property MESSAGE_QDRO_ADD_BENEFICIARY() As String
            Get
                Return ResourceManager.GetString("MESSAGE_QDRO_ADD_BENEFICIARY", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Insufficient funds for fee. Please review with management..
        '''</summary>
        Friend Shared ReadOnly Property MESSAGE_QDRO_AFTER_FEE_NEGATIVEBALANCE() As String
            Get
                Return ResourceManager.GetString("MESSAGE_QDRO_AFTER_FEE_NEGATIVEBALANCE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to QDRO Process cannot be completed for {0}. Please try again after month end for {1}..
        '''</summary>
        Friend Shared ReadOnly Property MESSAGE_QDRO_AFTER_MONTH_END() As String
            Get
                Return ResourceManager.GetString("MESSAGE_QDRO_AFTER_MONTH_END", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Amount Should be greater than 0 .
        '''</summary>
        Friend Shared ReadOnly Property MESSAGE_QDRO_AMOUNT_GREATER_THAN_ZERO() As String
            Get
                Return ResourceManager.GetString("MESSAGE_QDRO_AMOUNT_GREATER_THAN_ZERO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to A spouse recipient already added hence cannot add another recipient as spouse..
        '''</summary>
        Friend Shared ReadOnly Property MESSAGE_QDRO_ANOTHER_SPOUSE_NOT_ALLOWED() As String
            Get
                Return ResourceManager.GetString("MESSAGE_QDRO_ANOTHER_SPOUSE_NOT_ALLOWED", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Recipient Already Exist with this SSNo .
        '''</summary>
        Friend Shared ReadOnly Property MESSAGE_QDRO_BENEFICIARY_EXISTS() As String
            Get
                Return ResourceManager.GetString("MESSAGE_QDRO_BENEFICIARY_EXISTS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The length of beneficary first name cannot be more than 20 characters..
        '''</summary>
        Friend Shared ReadOnly Property MESSAGE_QDRO_BENEFICIARY_FIRST_NAME_MAX_LENGTH() As String
            Get
                Return ResourceManager.GetString("MESSAGE_QDRO_BENEFICIARY_FIRST_NAME_MAX_LENGTH", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The length of  beneficary last name cannot be more than 30 characters..
        '''</summary>
        Friend Shared ReadOnly Property MESSAGE_QDRO_BENEFICIARY_LAST_NAME_MAX_LENGTH() As String
            Get
                Return ResourceManager.GetString("MESSAGE_QDRO_BENEFICIARY_LAST_NAME_MAX_LENGTH", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The length of  beneficary middle name cannot be more than 20 characters..
        '''</summary>
        Friend Shared ReadOnly Property MESSAGE_QDRO_BENEFICIARY_MIDDLE_NAME_MAX_LENGTH() As String
            Get
                Return ResourceManager.GetString("MESSAGE_QDRO_BENEFICIARY_MIDDLE_NAME_MAX_LENGTH", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Condition for Adjustment is not Satisfied .
        '''</summary>
        Friend Shared ReadOnly Property MESSAGE_QDRO_CONDITION_FOR_ADJUSTMENT() As String
            Get
                Return ResourceManager.GetString("MESSAGE_QDRO_CONDITION_FOR_ADJUSTMENT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Deleted Successfully.
        '''</summary>
        Friend Shared ReadOnly Property MESSAGE_QDRO_DELETED_SUCCESSFULLY() As String
            Get
                Return ResourceManager.GetString("MESSAGE_QDRO_DELETED_SUCCESSFULLY", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to End Date cannot be greater than {0} . .
        '''</summary>
        Friend Shared ReadOnly Property MESSAGE_QDRO_END_DATE_GREATERTHAN() As String
            Get
                Return ResourceManager.GetString("MESSAGE_QDRO_END_DATE_GREATERTHAN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please Enter a date greater than 12/31/1995 .
        '''</summary>
        Friend Shared ReadOnly Property MESSAGE_QDRO_ENTER_DATE_GREATERTHAN() As String
            Get
                Return ResourceManager.GetString("MESSAGE_QDRO_ENTER_DATE_GREATERTHAN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &quot;Please enter the Mandatory fields.&quot; .
        '''</summary>
        Friend Shared ReadOnly Property MESSAGE_QDRO_ENTER_MANDATORY_FIELDS() As String
            Get
                Return ResourceManager.GetString("MESSAGE_QDRO_ENTER_MANDATORY_FIELDS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This search will take a longer time. It is suggested that you enter a search criteria. .
        '''</summary>
        Friend Shared ReadOnly Property MESSAGE_QDRO_ENTER_SEARCH_CRITERIA() As String
            Get
                Return ResourceManager.GetString("MESSAGE_QDRO_ENTER_SEARCH_CRITERIA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Enter a valid Amount to split .
        '''</summary>
        Friend Shared ReadOnly Property MESSAGE_QDRO_ENTER_VALID_AMOUNT_TO_SPLIT() As String
            Get
                Return ResourceManager.GetString("MESSAGE_QDRO_ENTER_VALID_AMOUNT_TO_SPLIT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please enter a valid SSN No. .
        '''</summary>
        Friend Shared ReadOnly Property MESSAGE_QDRO_ENTER_VALID_SSNO() As String
            Get
                Return ResourceManager.GetString("MESSAGE_QDRO_ENTER_VALID_SSNO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please review applied fees as it has been reset due to the action you have performed.
        '''</summary>
        Friend Shared ReadOnly Property MESSAGE_QDRO_FEE_RESET() As String
            Get
                Return ResourceManager.GetString("MESSAGE_QDRO_FEE_RESET", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Your split will be finalized, and a Fund ID and balances will be created for the alternate payee. Do you wish to save?.
        '''</summary>
        Friend Shared ReadOnly Property MESSAGE_QDRO_FINAL_SAVE_WARNING() As String
            Get
                Return ResourceManager.GetString("MESSAGE_QDRO_FINAL_SAVE_WARNING", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Do you wish to save?.
        '''</summary>
        Friend Shared ReadOnly Property MESSAGE_QDRO_FINAL_SAVE_WARNING_QUESTION() As String
            Get
                Return ResourceManager.GetString("MESSAGE_QDRO_FINAL_SAVE_WARNING_QUESTION", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Your split will be finalized, and a Fund ID and balances will be created for the alternate payee..
        '''</summary>
        Friend Shared ReadOnly Property MESSAGE_QDRO_FINAL_SAVE_WARNING_WITHOUT_QUESTION() As String
            Get
                Return ResourceManager.GetString("MESSAGE_QDRO_FINAL_SAVE_WARNING_WITHOUT_QUESTION", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The Alternate Payee   SSNO = {0}  is already a participant does not have a valid address record.  Processing cannot continue until the address is updated properly .
        '''</summary>
        Friend Shared ReadOnly Property MESSAGE_QDRO_INVALID_ADDRESS_RECORD() As String
            Get
                Return ResourceManager.GetString("MESSAGE_QDRO_INVALID_ADDRESS_RECORD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to There is Negative money in the account for this Plan Type. Please change the date range to Split. .
        '''</summary>
        Friend Shared ReadOnly Property MESSAGE_QDRO_NEGATIVE_AMOUNT_IN_PLAN() As String
            Get
                Return ResourceManager.GetString("MESSAGE_QDRO_NEGATIVE_AMOUNT_IN_PLAN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No fee has been applied..
        '''</summary>
        Friend Shared ReadOnly Property MESSAGE_QDRO_NO_FEE() As String
            Get
                Return ResourceManager.GetString("MESSAGE_QDRO_NO_FEE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to There is no money in the account for this Plan Type. Please change the Plan type to Split the account .
        '''</summary>
        Friend Shared ReadOnly Property MESSAGE_QDRO_NO_MONEY_IN_ACCOUNT() As String
            Get
                Return ResourceManager.GetString("MESSAGE_QDRO_NO_MONEY_IN_ACCOUNT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to First, make your selections for this Plan. If you also wish to split the other Plan, click Split button for this plan, then proceed to the second Plan before proceeding to the next stage..
        '''</summary>
        Friend Shared ReadOnly Property MESSAGE_QDRO_OTHER_PLAN_REMINDER() As String
            Get
                Return ResourceManager.GetString("MESSAGE_QDRO_OTHER_PLAN_REMINDER", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The requested split will result in a negative balance in one or more of the participant&apos;s accounts. Modify the split and try again..
        '''</summary>
        Friend Shared ReadOnly Property MESSAGE_QDRO_PARTICIPANT_CURRENT_BALANCE_IS_LESS_THAN_ZERO() As String
            Get
                Return ResourceManager.GetString("MESSAGE_QDRO_PARTICIPANT_CURRENT_BALANCE_IS_LESS_THAN_ZERO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Selected participant&apos;s data has been archived, Please unarchive the data to continue the process. .
        '''</summary>
        Friend Shared ReadOnly Property MESSAGE_QDRO_PARTICIPANT_DATA_ARCHIVED() As String
            Get
                Return ResourceManager.GetString("MESSAGE_QDRO_PARTICIPANT_DATA_ARCHIVED", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error occured while loading data. Please contact administrator..
        '''</summary>
        Friend Shared ReadOnly Property MESSAGE_QDRO_PARTICIPANT_DATA_LOADING_ERROR() As String
            Get
                Return ResourceManager.GetString("MESSAGE_QDRO_PARTICIPANT_DATA_LOADING_ERROR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Percentage can be upto 100 only. .
        '''</summary>
        Friend Shared ReadOnly Property MESSAGE_QDRO_PERCENTAGE_UPTO_100() As String
            Get
                Return ResourceManager.GetString("MESSAGE_QDRO_PERCENTAGE_UPTO_100", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Recipient cannot have same SSN No. .
        '''</summary>
        Friend Shared ReadOnly Property MESSAGE_QDRO_RECIEPENT_SSNO_SAME() As String
            Get
                Return ResourceManager.GetString("MESSAGE_QDRO_RECIEPENT_SSNO_SAME", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;BR/&gt;Failed – {0}&lt;BR/&gt; For failed request, please try creating them manually through the withdrawal requests screen as there may be some problem with the withdrawal service. .
        '''</summary>
        Friend Shared ReadOnly Property MESSAGE_QDRO_REQUEST_FAILED() As String
            Get
                Return ResourceManager.GetString("MESSAGE_QDRO_REQUEST_FAILED", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;BR/&gt;Following account(s) has been cashed out as balances were under $5,000. .
        '''</summary>
        Friend Shared ReadOnly Property MESSAGE_QDRO_REQUEST_FAILED_PASSED() As String
            Get
                Return ResourceManager.GetString("MESSAGE_QDRO_REQUEST_FAILED_PASSED", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The requested split will result in a negative balance in one or more of the participant&apos;s accounts. Modify the split and try again..
        '''</summary>
        Friend Shared ReadOnly Property MESSAGE_QDRO_REQUEST_NEGATIVEBALANCE() As String
            Get
                Return ResourceManager.GetString("MESSAGE_QDRO_REQUEST_NEGATIVEBALANCE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;BR/&gt; Passed – {0}. .
        '''</summary>
        Friend Shared ReadOnly Property MESSAGE_QDRO_REQUEST_PASSED() As String
            Get
                Return ResourceManager.GetString("MESSAGE_QDRO_REQUEST_PASSED", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to QDRO settlement completed. .
        '''</summary>
        Friend Shared ReadOnly Property MESSAGE_QDRO_SAVE_COMPLETED() As String
            Get
                Return ResourceManager.GetString("MESSAGE_QDRO_SAVE_COMPLETED", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unable to complete QDRO settlement. .
        '''</summary>
        Friend Shared ReadOnly Property MESSAGE_QDRO_SAVE_FAILED() As String
            Get
                Return ResourceManager.GetString("MESSAGE_QDRO_SAVE_FAILED", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to There is another Recipient Pending for Split..
        '''</summary>
        Friend Shared ReadOnly Property MESSAGE_QDRO_SAVE_RECORD_RECEIPENT_PENDING() As String
            Get
                Return ResourceManager.GetString("MESSAGE_QDRO_SAVE_RECORD_RECEIPENT_PENDING", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please Select the End Date .
        '''</summary>
        Friend Shared ReadOnly Property MESSAGE_QDRO_SELECT_END_DATE() As String
            Get
                Return ResourceManager.GetString("MESSAGE_QDRO_SELECT_END_DATE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Split Information not Found. .
        '''</summary>
        Friend Shared ReadOnly Property MESSAGE_QDRO_SPLIT_INFO_NOT_FOUND() As String
            Get
                Return ResourceManager.GetString("MESSAGE_QDRO_SPLIT_INFO_NOT_FOUND", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Split Not Possible .
        '''</summary>
        Friend Shared ReadOnly Property MESSAGE_QDRO_SPLIT_NOT_POSSIBE() As String
            Get
                Return ResourceManager.GetString("MESSAGE_QDRO_SPLIT_NOT_POSSIBE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please Enter the Split Percentage .
        '''</summary>
        Friend Shared ReadOnly Property MESSAGE_QDRO_SPLIT_PERCENTAGE() As String
            Get
                Return ResourceManager.GetString("MESSAGE_QDRO_SPLIT_PERCENTAGE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Start Date should not be greater than Current Date .
        '''</summary>
        Friend Shared ReadOnly Property MESSAGE_QDRO_STARTDATE_GREATERTHAN_CURRENTDATE() As String
            Get
                Return ResourceManager.GetString("MESSAGE_QDRO_STARTDATE_GREATERTHAN_CURRENTDATE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Start Date should not be greater than End Date .
        '''</summary>
        Friend Shared ReadOnly Property MESSAGE_QDRO_STARTDATE_GREATERTHAN_ENDDATE() As String
            Get
                Return ResourceManager.GetString("MESSAGE_QDRO_STARTDATE_GREATERTHAN_ENDDATE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to System can not Print/View the form/letter for failed/NA refund request Status. .
        '''</summary>
        Friend Shared ReadOnly Property MESSAGE_QDRO_STATUS_FAILED() As String
            Get
                Return ResourceManager.GetString("MESSAGE_QDRO_STATUS_FAILED", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Following is the list of Alternate Payee(s) having balances less than $5000 with their refund requests creation status. .
        '''</summary>
        Friend Shared ReadOnly Property MESSAGE_QDRO_STATUS_MESSAGE() As String
            Get
                Return ResourceManager.GetString("MESSAGE_QDRO_STATUS_MESSAGE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 1. Refund request will have to be created manually for recipient for whom  creation failed through this process. &lt;br /&gt; 2. You can also print/view these documents by visiting the link &lt;strong&gt; View IDM &lt;/strong&gt; available in the screen Maintenance Person -&gt; Documents Tab. .
        '''</summary>
        Friend Shared ReadOnly Property MESSAGE_QDRO_STATUS_NOTES() As String
            Get
                Return ResourceManager.GetString("MESSAGE_QDRO_STATUS_NOTES", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You have not printed/viewed the refund request Form and Letter. Are you sure you want to leave status tab. .
        '''</summary>
        Friend Shared ReadOnly Property MESSAGE_QDRO_STATUS_NOTVIEWED() As String
            Get
                Return ResourceManager.GetString("MESSAGE_QDRO_STATUS_NOTVIEWED", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unable to print/view the form/letter. .
        '''</summary>
        Friend Shared ReadOnly Property MESSAGE_QDRO_STATUS_REPORT_FAILED() As String
            Get
                Return ResourceManager.GetString("MESSAGE_QDRO_STATUS_REPORT_FAILED", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  It is mandatory that you print both the Letter &amp; Form of individual recipient by clicking on the respective icons associated with individual entries listed below. &lt;br /&gt; .
        '''</summary>
        Friend Shared ReadOnly Property MESSAGE_QDRO_STATUS_WARNING() As String
            Get
                Return ResourceManager.GetString("MESSAGE_QDRO_STATUS_WARNING", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sum of the amount to be given to the recipient is not equal to the amount to be split and so that the process cannot proceed .
        '''</summary>
        Friend Shared ReadOnly Property MESSAGE_QDRO_SUM_OF_AMOUNTS_GIVEN_NOTEQUAL_TOBE_SPLIT() As String
            Get
                Return ResourceManager.GetString("MESSAGE_QDRO_SUM_OF_AMOUNTS_GIVEN_NOTEQUAL_TOBE_SPLIT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Telephone number must be 10 digits..
        '''</summary>
        Friend Shared ReadOnly Property MESSAGE_QDRO_TELEPHONE_LENGTH() As String
            Get
                Return ResourceManager.GetString("MESSAGE_QDRO_TELEPHONE_LENGTH", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unfunded transactions exist prior to the QDRO End Date. Process cannot be completed .
        '''</summary>
        Friend Shared ReadOnly Property MESSAGE_QDRO_UNFUNDED_TRANSACIONS_EXISTS() As String
            Get
                Return ResourceManager.GetString("MESSAGE_QDRO_UNFUNDED_TRANSACIONS_EXISTS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Updated Successfully.
        '''</summary>
        Friend Shared ReadOnly Property MESSAGE_QDRO_UPDATED_SUCCESSFULLY() As String
            Get
                Return ResourceManager.GetString("MESSAGE_QDRO_UPDATED_SUCCESSFULLY", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Amount cannot have characters..
        '''</summary>
        Friend Shared ReadOnly Property MESSAGE_QRDO_AMOUNT_CHARACTERS() As String
            Get
                Return ResourceManager.GetString("MESSAGE_QRDO_AMOUNT_CHARACTERS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Total fee is 0, or fees not applicable?.
        '''</summary>
        Friend Shared ReadOnly Property MESSAGE_QRDO_FEES_NOT_DEFINED() As String
            Get
                Return ResourceManager.GetString("MESSAGE_QRDO_FEES_NOT_DEFINED", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid E-mail ID.
        '''</summary>
        Friend Shared ReadOnly Property MESSAGE_QRDO_INVALID_EMAILID() As String
            Get
                Return ResourceManager.GetString("MESSAGE_QRDO_INVALID_EMAILID", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please contact IT for support (ROPR)..
        '''</summary>
        Friend Shared ReadOnly Property MESSAGE_QRDO_NO_RT_FOR_FEE_ROPR() As String
            Get
                Return ResourceManager.GetString("MESSAGE_QRDO_NO_RT_FOR_FEE_ROPR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Percentage cannot have characters..
        '''</summary>
        Friend Shared ReadOnly Property MESSAGE_QRDO_PERCENTAGE_CHARACTERS() As String
            Get
                Return ResourceManager.GetString("MESSAGE_QRDO_PERCENTAGE_CHARACTERS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Split details for the {0} Plan have been reset..
        '''</summary>
        Friend Shared ReadOnly Property MESSAGE_QRDO_RESET() As String
            Get
                Return ResourceManager.GetString("MESSAGE_QRDO_RESET", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to A withdrawal, loan or other transaction has taken place after the assignment date entered.  Please review before proceeding. Do you wish to proceed?.
        '''</summary>
        Friend Shared ReadOnly Property MESSAGE_QRDO_SPLIT_ACCOUNT_WITHDRAWN_TDLOAN() As String
            Get
                Return ResourceManager.GetString("MESSAGE_QRDO_SPLIT_ACCOUNT_WITHDRAWN_TDLOAN", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
