'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.17929
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option or rebuild the Visual Studio project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class RegenerateRMDMessage
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Resources.RegenerateRMDMessage", Global.System.Reflection.[Assembly].Load("App_GlobalResources"))
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to RMD Batch process completed. Please verify the records..
        '''</summary>
        Friend Shared ReadOnly Property MESSAGE_BATCH_PROCESS() As String
            Get
                Return ResourceManager.GetString("MESSAGE_BATCH_PROCESS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please check the Regenerated RMD Records, Data is not proper..
        '''</summary>
        Friend Shared ReadOnly Property MESSAGE_CHECK_REGEN_RMD_RECORDS() As String
            Get
                Return ResourceManager.GetString("MESSAGE_CHECK_REGEN_RMD_RECORDS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Current RMD Date {0} is closed successfully..
        '''</summary>
        Friend Shared ReadOnly Property MESSAGE_CLOSED_SUCCESS() As String
            Get
                Return ResourceManager.GetString("MESSAGE_CLOSED_SUCCESS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to RMD records have not been created yet or current RMD already closed..
        '''</summary>
        Friend Shared ReadOnly Property MESSAGE_CLOSEED_OR_NODATE() As String
            Get
                Return ResourceManager.GetString("MESSAGE_CLOSEED_OR_NODATE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No Record exist for current RMD Process date. Please close current RMD to process next RMD date..
        '''</summary>
        Friend Shared ReadOnly Property MESSAGE_CLOSE_RMD_PROCESS() As String
            Get
                Return ResourceManager.GetString("MESSAGE_CLOSE_RMD_PROCESS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Are you sure you want to close current RMD Process !!!.
        '''</summary>
        Friend Shared ReadOnly Property MESSAGE_CONFIRM_CLOSE_RMD_PROCESS() As String
            Get
                Return ResourceManager.GetString("MESSAGE_CONFIRM_CLOSE_RMD_PROCESS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Are you sure you want to generate RMD records!!!.
        '''</summary>
        Friend Shared ReadOnly Property MESSAGE_CONFIRM_GENERATE() As String
            Get
                Return ResourceManager.GetString("MESSAGE_CONFIRM_GENERATE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please select MRD record(s) to generate Initial Letter..
        '''</summary>
        Friend Shared ReadOnly Property MESSAGE_ELIGIBLE_INITIAL_LETTER() As String
            Get
                Return ResourceManager.GetString("MESSAGE_ELIGIBLE_INITIAL_LETTER", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to First year RMD due date has passed.  Please modify expiration date via data correction to proceed with disbursement..
        '''</summary>
        Friend Shared ReadOnly Property MESSAGE_FIRST_YEAR_RMD() As String
            Get
                Return ResourceManager.GetString("MESSAGE_FIRST_YEAR_RMD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to RMD Records are generated successfully..
        '''</summary>
        Friend Shared ReadOnly Property MESSAGE_GENERATE_SUCCESS() As String
            Get
                Return ResourceManager.GetString("MESSAGE_GENERATE_SUCCESS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please set checkbox in participant maintenance screen to enroll annual RMD payments..
        '''</summary>
        Friend Shared ReadOnly Property MESSAGE_IS_ANNUAL_MRD_PAYMENT() As String
            Get
                Return ResourceManager.GetString("MESSAGE_IS_ANNUAL_MRD_PAYMENT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Before Processing RMD Records,Please Load RMD Records for processing..
        '''</summary>
        Friend Shared ReadOnly Property MESSAGE_LOAD_RECORDS_PROCESS() As String
            Get
                Return ResourceManager.GetString("MESSAGE_LOAD_RECORDS_PROCESS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Records are missing in the RMD factors (AtsMetaMinDistPeriods) table..
        '''</summary>
        Friend Shared ReadOnly Property MESSAGE_MISSING_RMD_FACTOR() As String
            Get
                Return ResourceManager.GetString("MESSAGE_MISSING_RMD_FACTOR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please update new taxrate in person maintenenace screen for this participant..
        '''</summary>
        Friend Shared ReadOnly Property MESSAGE_MRDTAXRATE() As String
            Get
                Return ResourceManager.GetString("MESSAGE_MRDTAXRATE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Multiple RMD payments required.  Please compute and update manually..
        '''</summary>
        Friend Shared ReadOnly Property MESSAGE_MULTIPLE_RMD_PAYMENTS() As String
            Get
                Return ResourceManager.GetString("MESSAGE_MULTIPLE_RMD_PAYMENTS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Selected participant is not eligible to generate RMD records..
        '''</summary>
        Friend Shared ReadOnly Property MESSAGE_NOT_ELIGIBLE_RMD() As String
            Get
                Return ResourceManager.GetString("MESSAGE_NOT_ELIGIBLE_RMD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No RMD record(s) exist!!!.
        '''</summary>
        Friend Shared ReadOnly Property MESSAGE_NO_RECORDS() As String
            Get
                Return ResourceManager.GetString("MESSAGE_NO_RECORDS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No RMD record(s) exist for the Year : @Year.
        '''</summary>
        Friend Shared ReadOnly Property MESSAGE_NO_RECORDS_FOR_YEAR() As String
            Get
                Return ResourceManager.GetString("MESSAGE_NO_RECORDS_FOR_YEAR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please select rmd records..
        '''</summary>
        Friend Shared ReadOnly Property MESSAGE_PRINT_LETTER() As String
            Get
                Return ResourceManager.GetString("MESSAGE_PRINT_LETTER", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Regenerate RMD is possible only for the present year..
        '''</summary>
        Friend Shared ReadOnly Property MESSAGE_REGEN_RMD_CURRENT_YEAR() As String
            Get
                Return ResourceManager.GetString("MESSAGE_REGEN_RMD_CURRENT_YEAR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Successfully Regenerated RMD Records..
        '''</summary>
        Friend Shared ReadOnly Property MESSAGE_REGEN_RMD_INSERTED() As String
            Get
                Return ResourceManager.GetString("MESSAGE_REGEN_RMD_INSERTED", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Current RMD Date is blank. Current RMD cannot be closed..
        '''</summary>
        Friend Shared ReadOnly Property MESSAGE_RMD_DATE_BLANK() As String
            Get
                Return ResourceManager.GetString("MESSAGE_RMD_DATE_BLANK", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to RMD records are not generated for Year {0}. Please generate RMD records for Year {0}..
        '''</summary>
        Friend Shared ReadOnly Property MESSAGE_RMD_GENERATE() As String
            Get
                Return ResourceManager.GetString("MESSAGE_RMD_GENERATE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No participant is eligible for initial letter..
        '''</summary>
        Friend Shared ReadOnly Property MESSAGE_SELECT_INITIAL_LETTERS() As String
            Get
                Return ResourceManager.GetString("MESSAGE_SELECT_INITIAL_LETTERS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please select the records for Batch Processing..
        '''</summary>
        Friend Shared ReadOnly Property MESSAGE_SELECT_RECORDS_BATCH_PROCESS() As String
            Get
                Return ResourceManager.GetString("MESSAGE_SELECT_RECORDS_BATCH_PROCESS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to There are @CntUnsatisfiedRMD participants who have unsatisfied RMD records. Do you want to continue?.
        '''</summary>
        Friend Shared ReadOnly Property MESSAGE_UNSATISFIED_RMD_CONTINUE() As String
            Get
                Return ResourceManager.GetString("MESSAGE_UNSATISFIED_RMD_CONTINUE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please verify if MRD_GRACE key has been properly defined in the configuration table..
        '''</summary>
        Friend Shared ReadOnly Property MESSAGE_VERIFY_MRD_GRACE_CONFIGURATION() As String
            Get
                Return ResourceManager.GetString("MESSAGE_VERIFY_MRD_GRACE_CONFIGURATION", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
