'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option or rebuild the Visual Studio project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class RetirementBatchEstimateMessages
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Resources.RetirementBatchEstimateMessages", Global.System.Reflection.[Assembly].Load("App_GlobalResources"))
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please select at least one record to add.
        '''</summary>
        Friend Shared ReadOnly Property MESSAGE_RETIREMENT_BATCH_ESTIMATE_ADD_LIST() As String
            Get
                Return ResourceManager.GetString("MESSAGE_RETIREMENT_BATCH_ESTIMATE_ADD_LIST", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Added to list.
        '''</summary>
        Friend Shared ReadOnly Property MESSAGE_RETIREMENT_BATCH_ESTIMATE_ADD_LIST_SUCCESS() As String
            Get
                Return ResourceManager.GetString("MESSAGE_RETIREMENT_BATCH_ESTIMATE_ADD_LIST_SUCCESS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Annuity Estimate based on both Retirement Plan and Savings Plan..
        '''</summary>
        Friend Shared ReadOnly Property MESSAGE_RETIREMENT_BATCH_ESTIMATE_ANNUTITY_BOTH() As String
            Get
                Return ResourceManager.GetString("MESSAGE_RETIREMENT_BATCH_ESTIMATE_ANNUTITY_BOTH", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Annuity Estimate based on Retirement Plan only..
        '''</summary>
        Friend Shared ReadOnly Property MESSAGE_RETIREMENT_BATCH_ESTIMATE_ANNUTITY_RETIREMENT() As String
            Get
                Return ResourceManager.GetString("MESSAGE_RETIREMENT_BATCH_ESTIMATE_ANNUTITY_RETIREMENT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Annuity Estimate based on Savings Plan only..
        '''</summary>
        Friend Shared ReadOnly Property MESSAGE_RETIREMENT_BATCH_ESTIMATE_ANNUTITY_SAVINGS() As String
            Get
                Return ResourceManager.GetString("MESSAGE_RETIREMENT_BATCH_ESTIMATE_ANNUTITY_SAVINGS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Assumption: Please enter the value in assumption box.
        '''</summary>
        Friend Shared ReadOnly Property MESSAGE_RETIREMENT_BATCH_ESTIMATE_ASSUMPTION_EMPTY() As String
            Get
                Return ResourceManager.GetString("MESSAGE_RETIREMENT_BATCH_ESTIMATE_ASSUMPTION_EMPTY", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Assumption: Should not be more than {0} character(s).
        '''</summary>
        Friend Shared ReadOnly Property MESSAGE_RETIREMENT_BATCH_ESTIMATE_ASSUMPTION_LENGTH() As String
            Get
                Return ResourceManager.GetString("MESSAGE_RETIREMENT_BATCH_ESTIMATE_ASSUMPTION_LENGTH", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to List removed from database.
        '''</summary>
        Friend Shared ReadOnly Property MESSAGE_RETIREMENT_BATCH_ESTIMATE_CLEAR_LIST() As String
            Get
                Return ResourceManager.GetString("MESSAGE_RETIREMENT_BATCH_ESTIMATE_CLEAR_LIST", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This will remove the participants that are saved in the database. Are your sure you wish to continue?.
        '''</summary>
        Friend Shared ReadOnly Property MESSAGE_RETIREMENT_BATCH_ESTIMATE_CLEAR_PARTICIPANTS() As String
            Get
                Return ResourceManager.GetString("MESSAGE_RETIREMENT_BATCH_ESTIMATE_CLEAR_PARTICIPANTS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Are you sure want to delete?.
        '''</summary>
        Friend Shared ReadOnly Property MESSAGE_RETIREMENT_BATCH_ESTIMATE_CONFIRMATION_DELETE() As String
            Get
                Return ResourceManager.GetString("MESSAGE_RETIREMENT_BATCH_ESTIMATE_CONFIRMATION_DELETE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to There are no items to deselect..
        '''</summary>
        Friend Shared ReadOnly Property MESSAGE_RETIREMENT_BATCH_ESTIMATE_DESELECT_ITEM() As String
            Get
                Return ResourceManager.GetString("MESSAGE_RETIREMENT_BATCH_ESTIMATE_DESELECT_ITEM", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Due to the age difference between you and the Survivor you have selected, this option is not available..
        '''</summary>
        Friend Shared ReadOnly Property MESSAGE_RETIREMENT_BATCH_ESTIMATE_DIFFERENCE_YOU_SURVIVOR() As String
            Get
                Return ResourceManager.GetString("MESSAGE_RETIREMENT_BATCH_ESTIMATE_DIFFERENCE_YOU_SURVIVOR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Future Salary Date: Should be greater than today&apos;s date.
        '''</summary>
        Friend Shared ReadOnly Property MESSAGE_RETIREMENT_BATCH_ESTIMATE_FUTURE_SAL_DATE() As String
            Get
                Return ResourceManager.GetString("MESSAGE_RETIREMENT_BATCH_ESTIMATE_FUTURE_SAL_DATE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Future Salary Date: Please enter the future salary date.
        '''</summary>
        Friend Shared ReadOnly Property MESSAGE_RETIREMENT_BATCH_ESTIMATE_FUTURE_SAL_EMPTY() As String
            Get
                Return ResourceManager.GetString("MESSAGE_RETIREMENT_BATCH_ESTIMATE_FUTURE_SAL_EMPTY", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Insufficient balance in {0} plan.
        '''</summary>
        Friend Shared ReadOnly Property MESSAGE_RETIREMENT_BATCH_ESTIMATE_INSUFFICIENT_BALANCE() As String
            Get
                Return ResourceManager.GetString("MESSAGE_RETIREMENT_BATCH_ESTIMATE_INSUFFICIENT_BALANCE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid Parameters Details.
        '''</summary>
        Friend Shared ReadOnly Property MESSAGE_RETIREMENT_BATCH_ESTIMATE_INVALID_PARAMETERS() As String
            Get
                Return ResourceManager.GetString("MESSAGE_RETIREMENT_BATCH_ESTIMATE_INVALID_PARAMETERS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to There are no saved items..
        '''</summary>
        Friend Shared ReadOnly Property MESSAGE_RETIREMENT_BATCH_ESTIMATE_NO_CLEAR_PARTICIPANTS() As String
            Get
                Return ResourceManager.GetString("MESSAGE_RETIREMENT_BATCH_ESTIMATE_NO_CLEAR_PARTICIPANTS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to There are no items..
        '''</summary>
        Friend Shared ReadOnly Property MESSAGE_RETIREMENT_BATCH_ESTIMATE_NO_ITEM() As String
            Get
                Return ResourceManager.GetString("MESSAGE_RETIREMENT_BATCH_ESTIMATE_NO_ITEM", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to There are not items to remove.
        '''</summary>
        Friend Shared ReadOnly Property MESSAGE_RETIREMENT_BATCH_ESTIMATE_NO_ITEMS() As String
            Get
                Return ResourceManager.GetString("MESSAGE_RETIREMENT_BATCH_ESTIMATE_NO_ITEMS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to There are no items to save..
        '''</summary>
        Friend Shared ReadOnly Property MESSAGE_RETIREMENT_BATCH_ESTIMATE_NO_SAVE_PARTICIPANTS() As String
            Get
                Return ResourceManager.GetString("MESSAGE_RETIREMENT_BATCH_ESTIMATE_NO_SAVE_PARTICIPANTS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to There are no saved items to retrieve..
        '''</summary>
        Friend Shared ReadOnly Property MESSAGE_RETIREMENT_BATCH_ESTIMATE_NO_SHOW_PARTICIPANTS() As String
            Get
                Return ResourceManager.GetString("MESSAGE_RETIREMENT_BATCH_ESTIMATE_NO_SHOW_PARTICIPANTS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Person has crossed the age specified for estimate.
        '''</summary>
        Friend Shared ReadOnly Property MESSAGE_RETIREMENT_BATCH_ESTIMATE_PERSON_CROSS_AGE() As String
            Get
                Return ResourceManager.GetString("MESSAGE_RETIREMENT_BATCH_ESTIMATE_PERSON_CROSS_AGE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to There are no items to remove..
        '''</summary>
        Friend Shared ReadOnly Property MESSAGE_RETIREMENT_BATCH_ESTIMATE_REMOVE_ITEM() As String
            Get
                Return ResourceManager.GetString("MESSAGE_RETIREMENT_BATCH_ESTIMATE_REMOVE_ITEM", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please select a participant to delete.
        '''</summary>
        Friend Shared ReadOnly Property MESSAGE_RETIREMENT_BATCH_ESTIMATE_REMOVE_LIST() As String
            Get
                Return ResourceManager.GetString("MESSAGE_RETIREMENT_BATCH_ESTIMATE_REMOVE_LIST", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Selected participants removed for this estimate.
        '''</summary>
        Friend Shared ReadOnly Property MESSAGE_RETIREMENT_BATCH_ESTIMATE_REMOVE_LIST_SUCCESS() As String
            Get
                Return ResourceManager.GetString("MESSAGE_RETIREMENT_BATCH_ESTIMATE_REMOVE_LIST_SUCCESS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Results truncated. Showing only {0} rows out of {1}.
        '''</summary>
        Friend Shared ReadOnly Property MESSAGE_RETIREMENT_BATCH_ESTIMATE_RESULTS_TRUNCATED() As String
            Get
                Return ResourceManager.GetString("MESSAGE_RETIREMENT_BATCH_ESTIMATE_RESULTS_TRUNCATED", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Currently selected participants saved to database for future use.
        '''</summary>
        Friend Shared ReadOnly Property MESSAGE_RETIREMENT_BATCH_ESTIMATE_SAVE_LIST() As String
            Get
                Return ResourceManager.GetString("MESSAGE_RETIREMENT_BATCH_ESTIMATE_SAVE_LIST", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No records to save.
        '''</summary>
        Friend Shared ReadOnly Property MESSAGE_RETIREMENT_BATCH_ESTIMATE_SAVE_LIST_VALIDATION() As String
            Get
                Return ResourceManager.GetString("MESSAGE_RETIREMENT_BATCH_ESTIMATE_SAVE_LIST_VALIDATION", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Saved.
        '''</summary>
        Friend Shared ReadOnly Property MESSAGE_RETIREMENT_BATCH_ESTIMATE_SAVE_PARAMETER() As String
            Get
                Return ResourceManager.GetString("MESSAGE_RETIREMENT_BATCH_ESTIMATE_SAVE_PARAMETER", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to All Participants will be saved to database. Continue?.
        '''</summary>
        Friend Shared ReadOnly Property MESSAGE_RETIREMENT_BATCH_ESTIMATE_SAVE_PARTICIPANTS() As String
            Get
                Return ResourceManager.GetString("MESSAGE_RETIREMENT_BATCH_ESTIMATE_SAVE_PARTICIPANTS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to There are no items to select..
        '''</summary>
        Friend Shared ReadOnly Property MESSAGE_RETIREMENT_BATCH_ESTIMATE_SELECT_ITEM() As String
            Get
                Return ResourceManager.GetString("MESSAGE_RETIREMENT_BATCH_ESTIMATE_SELECT_ITEM", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Warning: Your existing selections will be overwritten. Are your sure you wish to continue?.
        '''</summary>
        Friend Shared ReadOnly Property MESSAGE_RETIREMENT_BATCH_ESTIMATE_SHOW_PARTICIPANTS() As String
            Get
                Return ResourceManager.GetString("MESSAGE_RETIREMENT_BATCH_ESTIMATE_SHOW_PARTICIPANTS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unable to retrive account information.
        '''</summary>
        Friend Shared ReadOnly Property MESSAGE_RETIREMENT_BATCH_ESTIMATE_UNABLE_TO_RETRIEVE() As String
            Get
                Return ResourceManager.GetString("MESSAGE_RETIREMENT_BATCH_ESTIMATE_UNABLE_TO_RETRIEVE", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
