'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class CashApplicationFundingIndividual

    '''<summary>
    '''ScriptMgrProxyCashApplication control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptMgrProxyCashApplication As Global.System.Web.UI.ScriptManagerProxy

    '''<summary>
    '''HiddenFieldDirty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenFieldDirty As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''UpdatePanel2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel2 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''lblHdr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHdr As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''updtPnlTab control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updtPnlTab As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''tdSearchYMCA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdSearchYMCA As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''lnkSearchYMCA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkSearchYMCA As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lblSearchYMCA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSearchYMCA As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tdSearchPerson control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdSearchPerson As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''lnkSearchPerson control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkSearchPerson As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lblSearchPerson control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSearchPerson As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tdSelectTransaction control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdSelectTransaction As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''lnkSelectTransaction control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkSelectTransaction As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lblSelectTransaction control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSelectTransaction As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''up control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents up As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''MV control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MV As Global.System.Web.UI.WebControls.MultiView

    '''<summary>
    '''ViewYMCASearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ViewYMCASearch As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''trYmcaSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trYmcaSearch As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''spnSeletedYMCA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spnSeletedYMCA As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''LabelYmcaNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelYmcaNo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LabelYmcaName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelYmcaName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LabelCity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelCity As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LabelState control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelState As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TextBoxYmcaNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxYmcaNo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextBoxYmcaName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxYmcaName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextBoxCity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxCity As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TextBoxState control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxState As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnYmcaFind control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnYmcaFind As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnYmcaClear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnYmcaClear As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''spnSelectYMCA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spnSelectYMCA As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''LabelRecordNotFound control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelRecordNotFound As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''gvYmca control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvYmca As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''btnSearchYmcaClose control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSearchYmcaClose As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnSearchYmcaNext control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSearchYmcaNext As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''ViewTransmittal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ViewTransmittal As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''trSearchPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trSearchPanel As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''spnSelectedPerson control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spnSelectedPerson As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtSearchFundNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSearchFundNo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtSearchSSN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSearchSSN As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtSearchFirstName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSearchFirstName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtSearchLastName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSearchLastName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnPersonFind control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPersonFind As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnPersonClear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPersonClear As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''spnSelectPerson control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spnSelectPerson As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''gvPerson control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvPerson As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''divTransmittal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divTransmittal As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''spnSelectTransmittal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spnSelectTransmittal As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Span2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Span2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''gvTransmittal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvTransmittal As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''btnPersonPrevious control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPersonPrevious As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnPersonClose control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPersonClose As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnPersonNext control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPersonNext As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''ViewTransaction control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ViewTransaction As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''spnFundDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spnFundDetails As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''spnSelectedTransmittal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spnSelectedTransmittal As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblFundingDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFundingDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''dtUserFundeddate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dtUserFundeddate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rfDatevalidation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfDatevalidation As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''RangeValidatorUCDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RangeValidatorUCDate As Global.System.Web.UI.WebControls.RangeValidator

    '''<summary>
    '''lblAmountDue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAmountDue As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAmountPaid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAmountPaid As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAmountPaidNotUse control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAmountPaidNotUse As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCreditAvaiable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCreditAvaiable As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtAmountDue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAmountDue As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtAountPaid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAountPaid As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtAmountPaidNotUse control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAmountPaidNotUse As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''imgbtnAmountPaidNotUse control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgbtnAmountPaidNotUse As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''txtCreditAvailable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCreditAvailable As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''imgbtnCreditAvailable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgbtnCreditAvailable As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''spnReceipts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spnReceipts As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblReceiptNoRecord control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblReceiptNoRecord As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''gvReceipts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvReceipts As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''imgBtnReceipts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgBtnReceipts As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''gvTrn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvTrn As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''lblTransmitalAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTransmitalAmount As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTotalSelectedAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotalSelectedAmount As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTotalAppliedAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotalAppliedAmount As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnTransactionPrevious control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnTransactionPrevious As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnTransactionClose control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnTransactionClose As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnUpdateAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnUpdateAmount As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnTransactionProcess control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnTransactionProcess As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''PlaceHolderMessageBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PlaceHolderMessageBox As Global.System.Web.UI.WebControls.PlaceHolder
End Class
