'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class DARFileImport

    '''<summary>
    '''DARFileImportScriptManager control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DARFileImportScriptManager As Global.System.Web.UI.ScriptManagerProxy

    '''<summary>
    '''divDARImportFileSection control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divDARImportFileSection As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''btnImportDARBankResponseFile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnImportDARBankResponseFile As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''divDisplayImportedResultsSection control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divDisplayImportedResultsSection As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblDARImportRecordsInformaion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDARImportRecordsInformaion As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblRecords control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRecords As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''divDARImportSummary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divDARImportSummary As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblTotalGrossAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotalGrossAmount As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTotalGrossAmountValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotalGrossAmountValue As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblTotalStateTaxWithheld control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotalStateTaxWithheld As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTotalStateTaxWithheldValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotalStateTaxWithheldValue As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblTotalFedTaxWithheld control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotalFedTaxWithheld As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTotalFedTaxWithheldValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotalFedTaxWithheldValue As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblTotalLocalTaxWithheld control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotalLocalTaxWithheld As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTotalLocalTaxandOtherWithheldValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotalLocalTaxandOtherWithheldValue As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblTotalNetAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotalNetAmount As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTotalNetAmountValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotalNetAmountValue As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''btnPrintDARImportFileList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPrintDARImportFileList As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnRunDARImportFile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRunDARImportFile As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnDiscardDARImportFile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDiscardDARImportFile As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnClose control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnClose As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''divErrorDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divErrorDetails As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Button2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Button2 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnConfirmDialogYesRun control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnConfirmDialogYesRun As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnConfirmDialogYesDiscard control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnConfirmDialogYesDiscard As Global.System.Web.UI.WebControls.Button
End Class
