'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class DCToolsAddYMCACredit

    '''<summary>
    '''YMCACreditScriptManager control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents YMCACreditScriptManager As Global.System.Web.UI.ScriptManagerProxy

    '''<summary>
    '''uplYMCACredit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents uplYMCACredit As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''tdApplyCredit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdApplyCredit As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''tdReviewAndSubmit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdReviewAndSubmit As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''divApplyCredit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divApplyCredit As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblYMCAInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblYMCAInfo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblYMCANo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblYMCANo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDispYMCANo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDispYMCANo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblYMCAName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblYMCAName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDispYMCAName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDispYMCAName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCurrentCredit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCurrentCredit As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDispCurrentCredit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDispCurrentCredit As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAddCreditHeaderText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAddCreditHeaderText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAmount As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtReceivedDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtReceivedDate As Global.CustomControls.CalenderTextBox

    '''<summary>
    '''txtNotes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNotes As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''divReviewAndSubmit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divReviewAndSubmit As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblReviewHeaderText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblReviewHeaderText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblReviewYMCANo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblReviewYMCANo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblReviewDispYMCANo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblReviewDispYMCANo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblReviewYMCAName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblReviewYMCAName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblReviewDispYMCAName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblReviewDispYMCAName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblReviewCurrentCredit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblReviewCurrentCredit As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblReviewDispCurrentCredit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblReviewDispCurrentCredit As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblReviewAddedCredit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblReviewAddedCredit As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblReviewDispAddedCredit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblReviewDispAddedCredit As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblReviewTotalCredit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblReviewTotalCredit As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblReviewDispTotalCredit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblReviewDispTotalCredit As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblReviewCreditSrcCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblReviewCreditSrcCode As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblReviewDispCreditSrcCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblReviewDispCreditSrcCode As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblReviewRecdDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblReviewRecdDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblReviewDispRecdDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblReviewDispRecdDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblReviewRecdAcctDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblReviewRecdAcctDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblReviewDispRecdAcctDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblReviewDispRecdAcctDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblReviewNotes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblReviewNotes As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblReviewDispNotes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblReviewDispNotes As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnPrevious control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPrevious As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnNext control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnNext As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnSaveYMCACredit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSaveYMCACredit As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnClose control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnClose As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnConfirmDialogYes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnConfirmDialogYes As Global.System.Web.UI.WebControls.Button
End Class
