'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class LACLoansProcessing

    '''<summary>
    '''PlaceHolderSecurityCheck control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PlaceHolderSecurityCheck As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''upLoan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upLoan As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''Td1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Td1 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''Td2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Td2 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''Td3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Td3 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''Td4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Td4 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''Td5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Td5 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''Td6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Td6 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''lblFundId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFundId As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtFundNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFundNo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''chkCHECK control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkCHECK As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkEFT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkEFT As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''btnFind control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnFind As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnClear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnClear As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''gvLoansForProcessing control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvLoansForProcessing As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''lblRecords control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRecords As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''btnPrintList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPrintList As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnSaveOND control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSaveOND As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnDisburse control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDisburse As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnClose control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnClose As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''ConfirmDialog control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ConfirmDialog As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''tblConfirmTable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblConfirmTable As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''divConfirmBusinessDayProcessing control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divConfirmBusinessDayProcessing As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''trConfirmDialogYesNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trConfirmDialogYesNo As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''btnConfirmDialogYes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnConfirmDialogYes As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''tblProgressDialogNew control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblProgressDialogNew As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''spanProgressDialogStaticTotalCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spanProgressDialogStaticTotalCount As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''divCompletionDisplay control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divCompletionDisplay As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''spanProgressDialogRunningTotalCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spanProgressDialogRunningTotalCount As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''spanProgressDialogTotalCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spanProgressDialogTotalCount As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''divProgressBar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divProgressBar As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''spanLoanProcessingSummaryTotal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spanLoanProcessingSummaryTotal As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''btnCloseSummary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCloseSummary As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''UncheckONDDialogBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UncheckONDDialogBox As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''btnUncheckONDDialogBoxYes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnUncheckONDDialogBoxYes As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''CheckONDDialogBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckONDDialogBox As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''btnCheckONDDialogBoxYes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCheckONDDialogBoxYes As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''hdnSelectedLoanLoanRequestID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnSelectedLoanLoanRequestID As Global.System.Web.UI.WebControls.HiddenField
End Class
