'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class LACRate

    '''<summary>
    '''dbScriptManagerProxy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dbScriptManagerProxy As Global.System.Web.UI.ScriptManagerProxy

    '''<summary>
    '''PlaceHolderSecurityCheck control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PlaceHolderSecurityCheck As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''upLoan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upLoan As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''tdLoansApproval control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdLoansApproval As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''tdLoanProcessing control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdLoanProcessing As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''tdExceptions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdExceptions As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''tdSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdSearch As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''tdStatistics control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdStatistics As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''tdRate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdRate As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''lblCurrentPrimeRate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCurrentPrimeRate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblRate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNewPrimeRate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNewPrimeRate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtNewPrimeRate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNewPrimeRate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnEditRate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnEditRate As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnSaveRate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSaveRate As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnCancelRate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancelRate As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''gvLoan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvLoan As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''lblcount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblcount As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnClose control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnClose As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnConfirmDialogYes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnConfirmDialogYes As Global.System.Web.UI.WebControls.Button
End Class
