'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class RetirementEstimateBatchWebForm

    '''<summary>
    '''dbScriptManagerProxy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dbScriptManagerProxy As Global.System.Web.UI.ScriptManagerProxy

    '''<summary>
    '''upManageList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upManageList As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''LabelNoDataFound control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelNoDataFound As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_Search_MoreItems control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_Search_MoreItems As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LabelImportAssociation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelImportAssociation As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''chkList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkList As Global.System.Web.UI.WebControls.CheckBoxList

    '''<summary>
    '''upParameters control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upParameters As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''TextBoxFutureSalaryEffDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxFutureSalaryEffDate As Global.YMCAUI.DateUserControl

    '''<summary>
    '''rdFormToPrint control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdFormToPrint As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''LabelPraAssumption control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelPraAssumption As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LabelSubPraAssumptionForEligible control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelSubPraAssumptionForEligible As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TextBoxPraAssumption control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxPraAssumption As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''CustomValidatorAssumption control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CustomValidatorAssumption As Global.System.Web.UI.WebControls.CustomValidator

    '''<summary>
    '''LabelPraAssumptionForNonEligible control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelPraAssumptionForNonEligible As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LabelSubPraAssumptionForNonEligible control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LabelSubPraAssumptionForNonEligible As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TextBoxPraAssumptionForNonEligible control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxPraAssumptionForNonEligible As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ValidationSummaryRetirementEstimate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ValidationSummaryRetirementEstimate As Global.System.Web.UI.WebControls.ValidationSummary

    '''<summary>
    '''ButtonRemoveList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonRemoveList As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''UpdatePanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel1 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''ButtonSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonSave As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''ButtonShowList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonShowList As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnYes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnYes As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''labelMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents labelMessage As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''HiddenFieldSavedListCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenFieldSavedListCount As Global.System.Web.UI.WebControls.HiddenField
End Class
