'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class RMDPrintLetters

    '''<summary>
    '''RMDPRintScriptManager control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RMDPRintScriptManager As Global.System.Web.UI.ScriptManagerProxy

    '''<summary>
    '''uplGenerateRMD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents uplGenerateRMD As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''lblMRDMsg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMRDMsg As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lnkInitial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkInitial As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lbllnkInitial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbllnkInitial As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lnkFollowup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkFollowup As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lbllnkFollowup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbllnkFollowup As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lnkReprintLetter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkReprintLetter As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lbllnkReprintLetter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbllnkReprintLetter As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDescription As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''trFilterAccountLocked control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trFilterAccountLocked As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''trFilterAccountDDL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trFilterAccountDDL As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''ddlAcctLocked control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlAcctLocked As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''trFilterInsufficientBal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trFilterInsufficientBal As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''trFilterInsufficientBalDDL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trFilterInsufficientBalDDL As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''ddlInsufficientBal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlInsufficientBal As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblYears control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblYears As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlRMDYear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlRMDYear As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''trRMDBatchWiseDataControl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trRMDBatchWiseDataControl As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''divBatchTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divBatchTitle As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''rptRMDBatchIDs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptRMDBatchIDs As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''trFilterFollowupGenerated control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trFilterFollowupGenerated As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''txtFollowup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFollowup As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''trFilterFollowupGeneratedDDL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trFilterFollowupGeneratedDDL As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''ddlFollowUp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlFollowUp As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Table3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Table3 As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''txtFundId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFundId As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSearch As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''tdBatchWiseInformation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdBatchWiseInformation As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''divBatchwiseInformation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divBatchwiseInformation As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''divToShowReprintLinks control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divToShowReprintLinks As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lnkRMDRePrintInitialLetter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkRMDRePrintInitialLetter As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''spanPipeForCashout control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spanPipeForCashout As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lnkRMDRePrintCashoutLetter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkRMDRePrintCashoutLetter As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''divToShowReprintFollowupLink control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divToShowReprintFollowupLink As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lnkRMDRePrintFollowupLetter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkRMDRePrintFollowupLetter As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''spanPipeForCashoutFollowup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spanPipeForCashoutFollowup As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lnkRMDRePrintCashoutFollowupLetter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkRMDRePrintCashoutFollowupLetter As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''gvLetters control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvLetters As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''trColorCodingLegends control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trColorCodingLegends As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''tdCashoutLegends control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdCashoutLegends As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''tdFollowUpLegends control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdFollowUpLegends As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''tdFollow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdFollow As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''trColorCodingLegendsForReprintLetters control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trColorCodingLegendsForReprintLetters As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''btnPrintList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPrintList As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnPrintLetters control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPrintLetters As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnClose control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnClose As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BatchProcessProgressControl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BatchProcessProgressControl As Global.YMCAUI.BatchProcessProgressControl
End Class
