'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class StateWithholdingListingControl

    '''<summary>
    '''btnStateWithholdAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnStateWithholdAdd As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''DataGridStateWithholding control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DataGridStateWithholding As Global.System.Web.UI.WebControls.DataGrid

    '''<summary>
    '''trStateName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trStateName As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lblstateName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblstateName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''trDisbursement control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trDisbursement As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lblDisbursement control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDisbursement As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''trElected control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trElected As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lblElected control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblElected As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''trFlatamt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trFlatamt As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lblFlatamt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFlatamt As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''trNewYourkCity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trNewYourkCity As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lblNewYourkCity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNewYourkCity As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''trYonkers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trYonkers As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lblYonkers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblYonkers As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''trFederalWithhold control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trFederalWithhold As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lblpercentage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblpercentage As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblFederalWithhold control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFederalWithhold As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''trAdditionalAmt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trAdditionalAmt As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lblAdditionalAmt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAdditionalAmt As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''trMaritalStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trMaritalStatus As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lblMaritalStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMaritalStatus As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''trExemptions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trExemptions As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lblExemptions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblExemptions As Global.System.Web.UI.WebControls.Label
End Class
